[build]
  base = "WHCFC_Frontend"
  command = "npm install && npm run build"
  publish = "dist/whcfc-frontend/browser"

[context.production]
  branch = "main"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200